### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by BanMeNerd** [volcanicer/Ajit-Pai#5]
People may not know how the bot works, so you should add a !help command so they know! And add radio.

**Comment by volcanicer** [comment]
Hi there! I'll get to work on the help command, however the radio bit will have to wait for a far future release (perhaps when I get another contributor to help develop the project). Thanks for suggesting this.

**Comment by volcanicer** [comment]
Finished the command, will upload to GitHub tomorrow afternoon.
